/* 
declara uma função e chamar ela exemplo:

function soma (a, b) {      declarando a função 
    return a + b;           retornando a função
}

soma (3, 5);                chamando a função

*/



/* 
 o que é DOM - Document Object Model
 tudo que a gente tem disponivel naquele documento, que no caso seria nossa janela web, o browser(o navegador)
 simplicando é tipo uma estrutura dos elementos dentro da janela
*/


/* ACHO QUE ESSE FOI O PIOR MODULO QUE EU JÁ FIZ NESSE BOOTCAMP '-' IREI PULAR ELE *-* */